# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib 'GCMS'
#' @export
agilentImportMSFile <- function(file) {
    .Call('GCMS_agilentImportMSFile', PACKAGE = 'GCMS', file)
}

#' @export
agilentImportFromDir <- function(directory) {
    .Call('GCMS_agilentImportFromDir', PACKAGE = 'GCMS', directory)
}

